on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push (Main)
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v1
      - uses: actions/setup-node@master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
    
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.8

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('package-lock.json') }}
          path: |
            ~/.cache
            node_modules
            packages/${{ matrix.adapter }}/tests/node_modules

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Copy .env file
        run: |
          cp .env.ci .env

      - name: Build Inertia
        run: |
          npm install
          cd packages/core && npm run build
          cd ../${{ matrix.adapter }} && npm run build

      - name: Build Playground
        run: |
          cd playgrounds/${{ matrix.adapter }} && npm run build

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/